### ISSUE TITLE
bitbucket defaults to Home.md

### ISSUE THREAD

**Issue by gillyspy** [mistermicheels/markdown-notes-tree#12]
Bitbucket defaults to Home.md -- rather than a bitbucket specific option could there be an flag for the file name?

**Comment by mistermicheels** [comment]
Hi @gillyspy, I think I'd need some more info on this one.

I just took a quick look at Bitbucket docs and Bitbucket seems to follow the README file name convention used by GitHub and `markdown-notes-tree`: https://support.atlassian.com/bitbucket-cloud/docs/readme-content/.
In which context do you need Home.md rather than README.md?

Regarding a flag for file name: would this need to affect file names at every level of the tree? Only top level? ...

**Comment by gillyspy** [comment]
What can i say i'm on bitbucket and it uses Home.md as the default not README.md. BB still allows to created README.md files but Home.md is akin to index.html, etc. I'm not sure if this is a workspace setting.

would you agree that the implicit change of having the file name in the "environment" is more resilient? 
If you do then you're 99% of the way to supporting a dynamic values.  Whether you expose that as a command line option or not is definitely up to you.  

i'm currrently using markdown-notes-tree as a dependency in a private package -- would be nice to use this package as is when i publish it. For now i'm just using my fork (via npm link)

**Comment by mistermicheels** [comment]
@gillyspy I released a beta version [1.13.0-beta.0](https://www.npmjs.com/package/markdown-notes-tree/v/1.13.0-beta.0) that includes a `readmeFilename` option. Can you let me know if this works on your end?

**Comment by gillyspy** [comment]
this seems to work yes 👍
